---
- name: Create the system groups
  group:
    name: "devstack"
    state: "present"
    system: "yes"

- name: Create ssh keys for defined user
  user:
    name: "{{devstack_user}}"
    generate_ssh_key: "yes"
    shell: "/bin/bash"
    groups: "sudo,devstack"
    createhome: "yes"
    home: "{{devstack_user_home}}"

- name: Clone DevStack repository
  become: true
  become_user: devstack
  git:
    repo: "https://git.openstack.org/openstack-dev/devstack"
    dest: "{{ devstack_user_home }}/devstack-repo"
    version: "{{ devstack_git_branch }}"
    force: "yes"

- name: Drop local.conf
  become: true
  become_user: devstack
  copy:
    src: "local.conf"
    dest: "{{ devstack_user_home }}/devstack-repo/local.conf"

- name: Run stack.sh
  become: true
  become_user: devstack
  command: "{{ devstack_user_home }}/devstack-repo/stack.sh"
